# .github/workflows/code_review.yml
name: AI Code Review Committee

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # This tells the runner to execute the command inside the Syntax-Handler folder
        working-directory: ./Syntax-Handler 
        run: pip install -r requirements.txt

      - name: Run AI Review
        # This is also crucial. The python command must be run from here too.
        working-directory: ./Syntax-Handler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OLLAMA_HOST: ${{ secrets.OLLAMA_HOST_URL }}
        run: python review_pr.py