# .github/workflows/code_review.yml
name: AI Code Review Committee

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- This debug step is still useful ---
      - name: List files in the repository
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- We run the commands from the root directory, where the files are ---
      - name: Install dependencies
        # No 'working-directory' is needed if the file is in the root.
        run: pip install -r requirements.txt

      - name: Run AI Review
        # No 'working-directory' is needed here either.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OLLAMA_HOST: ${{ secrets.OLLAMA_HOST_URL }}
        run: python review_pr.py